version: "3.9"

services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - go-fiber-rabbitmq
    restart: always

  sender:
    container_name: sender
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile-sender
    environment:
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - go-fiber-rabbitmq
    depends_on:
      - message-broker

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile-consumer
    environment:
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - go-fiber-rabbitmq
    depends_on:
      - message-broker
      - sender

networks:
  go-fiber-rabbitmq:
    driver: bridge